name: Generate Snake Animation

on:
  schedule: # executa uma vez por dia (00:00 UTC)
    - cron: "0 0 * * *"
  workflow_dispatch: # permite rodar manualmente
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar a cobrinha 🐍
        uses: Platane/snk@v3
        with:
          github_user_name: peuccoelho
          outputs: dist/github-contribution-grid-snake.svg

      - name: Publicar no branch output
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
